### PR TITLE
fix a painful typo

### PR DESCRIPTION
**Pull request by nlfurniss**

### CODE REVIEW

**Comment by scalvert** [comment]
Ouch...thx

**Comment by scalvert** [comment]
Looks like this PR is getting bitten by the [babel bug](https://github.com/ember-app-scheduler/ember-app-scheduler/pull/714#issuecomment-636000578). Going to wait on that fix before we merge this.

**Comment by scalvert** [comment]
Looks like @rwjblue just published the new version of `ember-cli-babel` that fixed the issue. Thanks!

**Comment by rwjblue** [comment]
The babel issue should be resolved now (looks like CI is happy)

**Pull request merged**
