### PR TITLE
fix: invert `setupRouter` deprecation warning

### LINKED ISSUE #956: Erroneous deprecation warning?
Hi there,

I think there might be an issue with a deprecation warning recently added here:
https://github.com/ember-app-scheduler/ember-app-scheduler/blob/master/addon/scheduler.ts#L84

The second parameter of `deprecate()` is documented as follow:
> If **falsy**, the deprecation will be displayed.

Therefore, I wonder if `router instanceof Router` should instead be `!(router instanceof Router)` or `router instanceof RouterService`. 

When looking at the code in my debugger console, the code looks like this:
```js
(true && !(router instanceof Ember.Router) && Ember.deprecate('The use of Ember.Router in setupRouter is deprecated. Please use the router service.', router instanceof Ember.Router, {
  id: 'ember-app-scheduler.setupRouter',
  until: '6.0.0'
}));
```

Related issue: https://github.com/DockYard/ember-router-scroll/issues/271

I am not familiar with Ember deprecations, so apologies if I am mistaken :)

### PR DESCRIPTION
**Pull request by buschtoens**
Fix #956.

### CODE REVIEW

**Review by snewcomer — APPROVED** [review]
Supa!

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
@scalvert - Any chance you could do a release? (I'm afk for a bit)

**Comment by scalvert** [comment]
On it!

**Comment by scalvert** [comment]
https://github.com/ember-app-scheduler/ember-app-scheduler/releases/tag/v5.1.2

**Pull request merged**
